### ISSUE TITLE
wrong directory name in aisler_sma_v2.m

### ISSUE THREAD

**Issue by PinkMushroom** [toammann/MultilayerSMA2Coax#2]
model_dir = [parentDir, filesep, '**FreeCAD**_Aisler6LayerHD_SMA_v2'];

the directory name should be

**FreeCad**_Aisler6LayerHD_SMA_v2'

**Comment by toammann** [comment]
Hey,
I am not sure why this fails for you. The 'FreeCad_Aisler6LayerHD_SMA_v2' model directory is located one level above the working directory. This is the root repository folder (I called this parent directory).

The openEMS solver needs a full path to the *.stl file. I was unable to run it using relative paths.

The model_dir should contain a path like this:
` C:\\Users\\XXXX\\Desktop\\git\\Multilayer_SMA2Microstrip\\FreeCAD_Aisler6LayerHD_SMA_v2`

So, this should be correct. Please note that the windows file seperator "\\" must be escaped. So "\\" is replaced by "\\\\". If you run this on linux you must use the linux file seperators.

I have replaced the hardcoded file seperator to use the "filesep" octave function. Maybe this will enable the correct path for linux. However, I am not sure :)

```
model_dir = [parentDir, filesep, 'FreeCAD_Aisler6LayerHD_SMA_v2'];
model_dir = strrep(model_dir, filesep, [filesep, filesep]);
filesep_dbl = [filesep, filesep];
```

Regards

**Comment by PinkMushroom** [comment]
The directory is there, it's the directory name which is the problem.
Git clone created a directory
using "Cad" instead of "CAD"

**Comment by toammann** [comment]
Hey, thanks for pointing this out. Not sure why this happend. I have changed the directory name. I did not even see the difference in your first post, sorry :)
