### ISSUE TITLE
physical_constants undefined

### ISSUE THREAD

**Issue by PinkMushroom** [toammann/MultilayerSMA2Coax#3]
error: 'physical_constants' undefined near line 118, column 118
if you comment it out, then you get an undefined c0 error.
so apparently physical_constants is missing (perhaps a missing octave library?)

```

% Undersize the z-coordiante of the metal layers as suggested by Thorsten Liebing
% To compensate for floating point issues in  the stl import
% https://github.com/thliebig/openEMS-Project/discussions/43
float_tol = 100e-9; % units [mm]
%float_tol = 0.005; % units [mm]
#float_tol = 0;

physical_constants;
unit = 1e-3; % all units in [mm]

Er_lambda = 1;
lambda = c0/(f_stop*sqrt(Er_lambda));
mesh_res = lambda/unit/mes_res_lambda_div;

```

**Comment by toammann** [comment]
Hello PinkMushroom,
physical_constants is a part of openEMS. My installation directory for openEMS is `C:\openEMS`. So, pysical_constants should be located in the `matlab` subfolder. You can check this with the help octave command.

```
>> help physical_constants
'physical_constants' is a script from the file C:\openEMS\matlab\physical_constants.m
```

Is your openEMS installation visible to octave?

This command just loads some pysical constant variables in the workspace so, there is no need to rely on this. I have added the value for c0 EPS0 and MUE0 directly in the skript.

**Comment by PinkMushroom** [comment]
aha. I should have thought of that. I have OpenEMS installed from source but I believe you have to enable octave functionality when you build it. Since I was going to be using Python I may not have.

This may explain the other errors I am seeing.

yes- that was the problem. I had not added the matlab paths to the octave. 
I didn't realize this was a separate step, I thought the installation took care of it.
