### ISSUE TITLE
Rosenberger SMA Step model

### ISSUE THREAD

**Issue by oberstet** [toammann/MultilayerSMA2Coax#5]
first of all, thank you so much for doing this work, specifically also using OSS, and for publishing your work again as OSS!  awesome!

by coincidence, I'm using exactly this part and got exactly the problem you tackle (https://community.aisler.net/t/how-to-correct-this-complex-pcb-outline-with-cutouts/3270). well, I only need sub-ghz, but obviously I still need to fit the part physically.

anyways, just a detail, but I stumbled across "Rosenberger does not provide CAD a model for their part" in the project readme .. maybe just outdated, as they do in fact provide a Step model

https://products.rosenberger.com/radio-frequency/connectors/157634/32k242-40ml5-right-angle-jack-pcb

but they do _not_ provide an electronic footprint! unfortunately only old-school CAD drawing.

which is why every user will have to redo/repeat work. not ideal. why don't they provide complete models and publish to snapeda or ultralibrarian or whatever?

will you publish it there as well?

> caveat: I have no idea whether those sites allow that, legal stuff etc. I'm a PCB newbie that just failed to create a proper footprint for this part, but I wouldn't publish it anyways as I'm just not confident enough in this area - I'm mostly a software guy;)

**Comment by oberstet** [comment]
here: 

![grafik](https://github.com/toammann/Multilayer_SMA2Microstrip/assets/233340/c3f0de70-3550-4e66-8585-2af2e961b389)

> note: seems I still haven't understood how/where kicad looks for footprints .. I tried the rosenberger step model within your existing design .. but well. anyways. that should be fixable.

**Comment by toammann** [comment]
Hey oberstet,
Thanks for your comments!

>  maybe just outdated, as they do in fact provide a Step model

Thats a good find, I spent quite some time looking for a CAD model. I asked rosenberger via email to provide one. So, this model is definitly new. I will add it to footprint!.

> which is why every user will have to redo/repeat work. not ideal. why don't they provide complete models and publish to snapeda or ultralibrarian or whatever?

Unfortunenately, this is not possible for RF-Parts of this kind. The connector is rated up to 18GHz where the pad capacitance GND return current inductance and all these little parasitics have a big influence on the connector performance.

These parasitics will vary greatly with with diffrent substrate materials (varying permittivity). So, if you were to design a footprint for a stackup which uses e.g. the RO4350 (Er=3.5) RF laminate you are likely to use an EM simulator to optimize the pyscial dimensions of the pad structures and via placements and so on. 

If you want to use the same footprint now on a FR4 susbstrate (Er=4.5) the permittivity is another one and therefore all the dimensions will be off slightly which will result in reduced performance at the higher frequencies.

Therefore, a footprint of aconnector is valid for ONE layer stack with defined substrate materials only. This is true for RF connectors in general.

If you want to use the RF connector only up to 1GHz or so it will not matter so much of course.

Regards,
Tobias

**Comment by toammann** [comment]
Hey,
i noticed, that the board outline is not rendered correctly in your Board. This is due to the user defined bridges. Aisler requires them to be defined in the edge cuts layer witch results in this rendering issue. Just delete them and it should render correctly..

https://community.aisler.net/t/custom-bridges-and-frames/49

I think it is a good idea to write a short section on "How to use the footprint". The are a few things that must be considred...

Regards

**Comment by oberstet** [comment]
> Thats a good find, I spent quite some time looking for a CAD model. I asked rosenberger via email to provide one. So, this model is definitly new. I will add it to footprint!.

great, thanks a lot!

just one note: it might be good/safe to add some note next to the license file that even though your repo/material is CC0/MIT (awesome!), the Rosenberger STEP file is not. surprisingly (I just verified), to download that file, I didn't need to register or even sign anything, and I haven't found/seen a license file - the only thing that one is shown is a note about "we are not liable if things go south". which is fine for me;)

> Therefore, a footprint of aconnector is valid for ONE layer stack with defined substrate materials only. This is true for RF connectors in general.

ok, understood. I wasn't aware. I only have limited understanding of RF stuff, and pretty much zero experience;) thanks for explaining!

my hope is, for sub-ghz (430-880mhz), I can get sth done/working nevertheless. fwiw, I want to create a handheld Linux + RT cognitive radio with dual RF and both built-in planar helical antennas and external connectors. but actually, being a SW guy, I want to get back/up to bits as fast as possible;)

> i noticed, that the board outline is not rendered correctly ...

ahh, ok, I have to read up / dig into that. thanks!

> I think it is a good idea to write a short section on "How to use the footprint".

that would be fantastic!

also, ideally, a user (well, at least me) would like to just drop a symbol/footprint lib for the part into his/her project, and then just use it without fiddling with paths or what

or even better: add a tagged release of a GH repo to his/her git repo as a submodule

https://git-scm.com/book/en/v2/Git-Tools-Submodules

that way, I could just sync with upstream to easily follow updates.

not sure if there is an established best practice in the KiCad community how people share and sync parts across projects using Git ... source driven collaboration etc

**Comment by toammann** [comment]
Hello,
I have releaed an update of the connector. I made changes but I did not order a board so far to test the changes. To get around the licensing issues I added my self drawn connector footprint from the FreeCAD 3D model. 

Regards
Tobias

**Comment by oberstet** [comment]
fantastic!! thanks a lot=)

I will test/use that soonish. currently I'm still figuring out my antenna in openEMS .. focusing on 446-930mhz skipping 223mhz- .. I've recognized now it is quite a challenge already fitting into the dimensions, and fully planar .. anyways ... I got coiled helical for those freqs working with quite good S11 ... but not in the dims and not planar ... atm fighting with dump and viewing 3d E-fields in paraview ..

> To get around the licensing issues I added my self drawn connector footprint from the FreeCAD 3D model.

+1 .. that's a safe bet;)
